### ISSUE TITLE
Verify with an exp claim throws exception with gem installed from Rubygems

### ISSUE THREAD

**Issue by grempe** [garyf/jwt_claims#1]
The `jwt_claims` gem was installed from Rubygems today.

Sample console test:

```
[2] pry(main)> require 'jwt_claims'
=> true
[3] pry(main)> jwt = JsonWebToken.sign({foo: 'bar', exp: Time.now.to_i}, key: 'gZH75aKtMN3Yj0iPS4hcgUuTwjAzZr9C')
=> "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmb28iOiJiYXIiLCJleHAiOjE0NzU4MTgzOTN9.gAcGss07BPjPGrhhnX-YDKpaMII69nptcnzzl8Cz00k"
[4] pry(main)> JsonWebToken.verify(jwt, key: 'gZH75aKtMN3Yj0iPS4hcgUuTwjAzZr9C')
=> {:ok=>{:foo=>"bar", :exp=>1475818393}}
[5] pry(main)> JwtClaims.verify(jwt, key: 'gZH75aKtMN3Yj0iPS4hcgUuTwjAzZr9C')
NameError: uninitialized constant JwtClaims::Validation::Claim
Did you mean?  JwtClaims
from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jwt_claims-0.0.2/lib/jwt_claims/validation.rb:27:in `registered_claim'
[6] pry(main)>
```

I think the rspec tests are passing since they explicitly require the classes needed. I don't think the lib dir code is doing that properly.

https://github.com/garyf/jwt_claims/blob/master/spec/jwt_claims/claim/exp_spec.rb#L1

I get failing specs with this issue if I run spec files directly.  For example:

```
bundle exec rspec spec/jwt_claims/validation_spec.rb
```

```
2) JwtClaims::Validation example data #rejected w all registered claims invalid returns array of failed claims
     Failure/Error:
       when :aud then Claim::Aud
       when :exp then Claim::Exp
       when :iat then Claim::Iat
       when :iss then Claim::Iss
       when :jti then Claim::Jti
       when :nbf then Claim::Nbf
       when :sub then Claim::Sub
       else nil # custom claim

     NameError:
       uninitialized constant JwtClaims::Validation::Claim
       Did you mean?  JwtClaims
     # ./lib/jwt_claims/validation.rb:26:in `registered_claim'
     # ./lib/jwt_claims/validation.rb:20:in `reject'
     # ./lib/jwt_claims/validation.rb:14:in `block in rejected'
     # ./lib/jwt_claims/validation.rb:13:in `each'
     # ./lib/jwt_claims/validation.rb:13:in `each_with_object'
     # ./lib/jwt_claims/validation.rb:13:in `rejected'
     # ./spec/jwt_claims/validation_spec.rb:55:in `block (5 levels) in <module:JwtClaims>'
```

I am submitting a pull request which I believe resolves these issues.  A new release would need to be pushed to Rubygems.

**Comment by grempe** [comment]
Thanks for merging and for pushing the new release of jwt_claims Gary.  I have a Rack Auth middleware using this that I am finishing up.  I'll send you a link for feedback if you don't mind.

Cheers,

Glenn
